# Generated by Django 3.0.2 on 2020-06-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
                ('reporter', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
